apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-client
  namespace: oran-o2ims
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oran-o2ims-test-client-role
rules:
  - nonResourceURLs:
      - /o2ims-infrastructureInventory/*
    verbs:
      - get
      - create
      - delete
      - update
      - patch
  - nonResourceURLs:
      - /o2ims-infrastructureMonitoring/*
    verbs:
      - get
  #- nonResourceURLs:
  #    - /o2ims-infrastructureInventory/v1/subscriptions
  #  verbs:
  #    - create
  #- nonResourceURLs:
  #    - /o2ims-infrastructureInventory/v1/subscriptions/*
  #  verbs:
  #    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oran-o2ims-test-client-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oran-o2ims-test-client-role
subjects:
  - kind: ServiceAccount
    name: test-client
    namespace: oran-o2ims
